baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Dan Carpenter"
theme = "anatole"
summarylength = 10
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
title = "Hello, I'm Dan Carpenter"
author = "Dan Carpenter"
description = "Ecologist and environmental data scientist using digital tech to aid decision making."
profilePicture = "images/dc_temp.jpg"
keywords = "ecology, R, QGIS"
favicon = "favicons/"
customCss = []
mainSections = ["post"]
dateFormat = "2020-06-28"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dan-carpenter-cenv-057b512a/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/drdcarpenter/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/drdcarpenter/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:drdcarpenter@googlemail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
  
  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
  
  [[menu.main]]
  name = "CV"
  weight = 500
  identifier = "cv"
  url = "/cv/"
  
  [[menu.main]]
  name = "Apps"
  weight = 600
  identifier = "apps"
  url = "https://app-dan-carpenter.co.uk"
  
