---
title: Natural Tranquility
author: Dan Carpenter
date: '2020-06-29'
slug: natural-tranquility
categories:
  - R
tags: []
Description: 'Tranquility and the ntm package'
Tags: []
Categories: []
DisableComments: no
---

## What is tranquility?
Tranquility is feelings of calm, serenity, peace.  People find tranquility in different places, such as a spa, or a quiet comfortable room.  But many people find tranquility in nature, in spaces full of natural sound away from the noise and chaos of modern life.  And it is these spaces of natural tranquility that I am interested in.

## Why am I interested in tranquility?
Green spaces in the UK are under pressure.  Many local authorities lack the funding necessary to maintain them, let alone enhance them.  There is pressure to deliver new housing, schools and other buildings and green spaces are often locations for these developments.  But as the UK lockdown resulting from the coronavirus pandemic has shown, green spaces are really important for our health and well-being.  Our local park has been a lifeline to us for exercise and many others have found comfort and solace in nature.

So green spaces are really important as places to relax, exercise and escape the stress of daily life.  And to be tranquil they need to be green, calm and full of natural sound.  Hearing the birds singing, the wind in the trees, or the sound of moving water is calming.  If green spaces are well away from human sound, they can be oases of calm.  However, too much human sound (traffic, aircraft, other human noises) reduces the tranquility of a space and it is less calming.  Nonetheless, a green spaces in an urban area can still be relatively tranquil compared to a busy street.

It is therefore really important to protect these spaces and ensure they remain tranquil so that people can benefit from spending time in them.  To do this though, we need to know how tranquil a space is and what the risks are to that tranquility, particularly from new projects, such as housing developments or new roads.

I have been involved in a project with the George Institute at the University of Oxford which is deploying [AudioMoth](https://www.openacousticdevices.info/) units in greenspaces in Oxfordshire.  The aim is to understand the naturalness of these greenspaces.  The plan is to use automatic classification of sound from the recordings to measure the soundscapes against some indices.  More information on the project can be found on [the website](https://www.greenspacehack.com/project/nature_sensing.html).

I am interested in whether automated audio recording and the Natural Tranquility Method are compatible.

## Measuring tranquility - introducing the NTM
The Natural Tranquility Method (Bentley 2019) is a way to measure tranquility based on the quantity and quality of sound.  Clive Bentley, the originator of the NTM, has published a book describing this method, called Tranquil Spaces.  You can read more about it on the [Natural Tranquility website](https://naturaltranquillity.com/).

That Natural Tranquility Method uses four parameters to define tranquility.  These are:

* NAMM - a rating from 1 - 5 of how much natural or man-made sound there is in a space
* PONS - the percentage of natural sound
* Lrr - the noise contribution of road and rail (in decibels)
* Lat - the total overall level of sound (in decibels)

Feeding these values into an algorithm calculates the probability of recording each tranquility score.  The maximum probability is selected as the tranquility score for that location.  Much more detail is available in the book!

## The ntm package
The Sharps Redmore website provides an online calculator for tranquility scores or levels.  I wanted to write an R package to calculate these scores instead.  I do a lot of work in R - it is my preferred way of interactive with and analysing data.  For me an R package to calculate tranquility scores make sense.  So I wrote one!  It is my first package - it is very simple and niche, but it was a very useful learning exercise.

The ntm package calculates a tranquility score for either a single location when provided with NAMM, PONS, Lrr and Lat values, or tranquility scores for a dataframe of these values.  You can find out more about the package on [its website](https://drdcarpenter.github.io/ntm/).

## Next steps
Writing an R package for the Natural Tranquility Method was a satisfying achievement.  But there is more I want to do.

I have been reading about the plumber R package and I would like to replicate the Natural Tranquility calculator using an api written in R.  This is a work in progress.  I need to work out what gets returned from the ntm_score() function in the ntm package (I think this is a string surrounded by html tags) and also how to send data from an html form to the api.

## Longer term ambitions
I also want to explore AudioMoth data and acoustic indices to see if it is possible to get at similar qualities of a soundscape as those required for the NTM.  This would mean it was quicker to collect multiple measurements of tranquility across a longer time period that can be achieved in a single site visit.  I am hoping data from the nature sensing project can be used for this.

If this proves to be possible, I would like to carry out a survey using volunteer deployment of AudioMoth recorders across a landscape (e.g. county) to measure tranquility over a wide area.  I think this will be really important for identifying places that are tranquil and protecting them from increases in man-made sound.
